# Generated by Django 4.2.19 on 2025-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_food_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
