# Generated by Django 4.2.19 on 2025-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_cartitem_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
